# Generated by Django 5.1.3 on 2026-04-14 18:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=255)),
                (
                    "account_group",
                    models.CharField(
                        choices=[
                            ("ASSET", "Asset"),
                            ("LIABILITY", "Liability"),
                            ("EQUITY", "Equity"),
                            ("REVENUE", "Revenue"),
                            ("COGS", "Cost of Goods Sold"),
                            ("EXPENSE", "Expense"),
                            ("TAX", "Tax"),
                            ("PURCHASE", "Purchase"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "account_nature",
                    models.CharField(
                        choices=[("DEBIT", "Debit"), ("CREDIT", "Credit")],
                        max_length=10,
                    ),
                ),
                ("level", models.PositiveSmallIntegerField()),
                ("is_postable", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "db_table": "accounts",
                "ordering": ["code"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "code"], name="accounts_tenant__a0e19b_idx"
                    ),
                    models.Index(
                        fields=["tenant_id", "parent"],
                        name="accounts_tenant__0a602f_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("tenant_id", "code"),
                        name="unique_active_account_code_per_tenant",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("tenant_id", "parent", "name"),
                        name="unique_account_name_per_parent_per_tenant",
                    ),
                ],
            },
        ),
    ]
