# Generated by Django 5.1.3 on 2026-04-21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_account_account_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tenant_id", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("date", models.DateField()),
                ("reference", models.CharField(max_length=50)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("PURCHASE_INVOICE", "Purchase Invoice"),
                            ("PURCHASE_RETURN", "Purchase Return"),
                            ("PURCHASE_BANK_PAYMENT", "Purchase Bank Payment"),
                            ("SALES_INVOICE", "Sales Invoice"),
                            ("SALES_RETURN", "Sales Return"),
                            ("SALES_BANK_RECEIPT", "Sales Bank Receipt"),
                        ],
                        max_length=40,
                    ),
                ),
                ("source_id", models.UUIDField()),
                ("document_type", models.CharField(max_length=80)),
                ("description", models.TextField(blank=True, default="")),
                ("people_type", models.CharField(blank=True, default="", max_length=20)),
                ("people_name", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "ordering": ["date", "reference"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("tenant_id", "source_type", "source_id"),
                        name="unique_active_journal_entry_per_source",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="JournalLine",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tenant_id", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("debit", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("credit", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("line_description", models.TextField(blank=True, default="")),
                ("people_type", models.CharField(blank=True, default="", max_length=20)),
                ("people_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_lines",
                        to="accounts.account",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="accounts.journalentry",
                    ),
                ),
            ],
            options={"ordering": ["created_at", "id"]},
        ),
    ]
