# Generated by Django 5.2.7 on 2026-05-10 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_inquiry_admin_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parent_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='tenant_role',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='ui_permissions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
