# Generated by Django 5.1.3 on 2026-04-21

from django.db import migrations, models


def set_existing_bank_account_types(apps, schema_editor):
    Account = apps.get_model("accounts", "Account")
    PurchaseBankPayment = apps.get_model("purchase", "PurchaseBankPayment")
    SalesBankReceipt = apps.get_model("sales", "SalesBankReceipt")

    bank_account_ids = set(
        PurchaseBankPayment.objects.filter(deleted_at__isnull=True).values_list(
            "bank_account_id", flat=True
        )
    )
    bank_account_ids.update(
        SalesBankReceipt.objects.filter(deleted_at__isnull=True).values_list(
            "bank_account_id", flat=True
        )
    )

    if bank_account_ids:
        Account.objects.filter(id__in=bank_account_ids).update(account_type="BANK")


def reset_existing_bank_account_types(apps, schema_editor):
    Account = apps.get_model("accounts", "Account")
    Account.objects.filter(account_type="BANK").update(account_type="GENERAL")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_account"),
        ("purchase", "0003_purchasebankpayment"),
        ("sales", "0003_salesbankreceipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("GENERAL", "General"),
                    ("BANK", "Bank"),
                    ("CASH", "Cash"),
                    ("RECEIVABLE", "Receivable"),
                    ("PAYABLE", "Payable"),
                    ("INVENTORY", "Inventory"),
                    ("REVENUE", "Revenue"),
                    ("COGS", "Cost of Goods Sold"),
                ],
                default="GENERAL",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            set_existing_bank_account_types,
            reverse_code=reset_existing_bank_account_types,
        ),
    ]
