# Generated by Django 5.1.3 on 2026-04-22

from django.db import migrations


def infer_legacy_account_types(apps, schema_editor):
    Account = apps.get_model("accounts", "Account")

    accounts = Account.objects.filter(
        deleted_at__isnull=True,
        account_type="GENERAL",
        is_postable=True,
    )

    for account in accounts.iterator():
        name = (account.name or "").strip().lower()
        next_type = None

        if account.account_group == "ASSET":
            if "bank" in name or account.code == "1110":
                next_type = "BANK"
            elif "cash" in name:
                next_type = "CASH"
            elif "receivable" in name:
                next_type = "RECEIVABLE"
            elif "inventory" in name:
                next_type = "INVENTORY"
        elif account.account_group == "LIABILITY":
            if "payable" in name:
                next_type = "PAYABLE"
        elif account.account_group == "REVENUE":
            next_type = "REVENUE"
        elif account.account_group == "COGS":
            next_type = "COGS"

        if next_type:
            account.account_type = next_type
            account.save(update_fields=["account_type"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_journalentry_journalline"),
    ]

    operations = [
        migrations.RunPython(infer_legacy_account_types, reverse_code=migrations.RunPython.noop),
    ]
