# Generated by Django 5.2.7 on 2026-04-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_dimension'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_dimensions',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.dimension'),
        ),
        migrations.AddField(
            model_name='user',
            name='business_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='tenant_limit',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
