# Generated by Django 5.2.7 on 2026-04-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='admin_reply',
            field=models.TextField(blank=True, default=''),
        ),
    ]
