# Generated by Django 5.1.3 on 2026-05-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salesbankreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceline',
            name='cost_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='cost_used',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
