# Generated by Django 5.1.3 on 2026-06-11 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_salesman'),
        ('sales', '0004_salesinvoiceline_cost_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='salesman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='inventory.salesman'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='salesman_commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='salesman_commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
