# Generated by Django 5.2.7 on 2026-05-04 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_product_confirmed_unit_cost_product_direct_price_and_more'),
        ('purchase', '0003_purchasebankpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='item_type',
            field=models.CharField(choices=[('RAW_MATERIAL', 'Raw Material'), ('FINISHED_GOOD', 'Finished Good')], default='FINISHED_GOOD', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoice_lines', to='inventory.rawmaterial'),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.unit'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoice_lines', to='inventory.product'),
        ),
    ]
