# Generated by Django 5.2.7 on 2026-05-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_purchaseinvoiceline_item_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
