# Generated by Django 5.1.3 on 2026-04-14 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_account"),
        ("inventory", "0003_alter_brand_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.account",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="cogs_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cogs_products",
                to="accounts.account",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="inventory_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_products",
                to="accounts.account",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="revenue_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revenue_products",
                to="accounts.account",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.account",
            ),
        ),
    ]
