# Generated by Django 5.1.3 on 2026-04-14 18:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_account"),
        ("inventory", "0004_customer_account_product_cogs_account_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
            ],
        ),
        migrations.RemoveIndex(
            model_name="openingstock",
            name="inventory_o_tenant__d7c8c0_idx",
        ),
        migrations.RemoveIndex(
            model_name="openingstock",
            name="inventory_o_tenant__28986a_idx",
        ),
        migrations.RenameField(
            model_name="openingstock",
            old_name="purchase_quantity",
            new_name="quantity",
        ),
        migrations.RemoveField(
            model_name="openingstock",
            name="selling_quantity",
        ),
        migrations.RemoveField(
            model_name="product",
            name="materials",
        ),
        migrations.RemoveField(
            model_name="rawmaterial",
            name="quantity",
        ),
        migrations.AddField(
            model_name="category",
            name="cogs_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="category_cogs",
                to="accounts.account",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="inventory_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="category_inventory",
                to="accounts.account",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="revenue_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="category_revenue",
                to="accounts.account",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.category",
            ),
        ),
        migrations.AddField(
            model_name="productmaterial",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materials",
                to="inventory.product",
            ),
        ),
        migrations.AddField(
            model_name="rawmaterial",
            name="inventory_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.account",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="cogs_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_cogs",
                to="accounts.account",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="inventory_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_inventory",
                to="accounts.account",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="revenue_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_revenue",
                to="accounts.account",
            ),
        ),
        migrations.AlterField(
            model_name="productmaterial",
            name="raw_material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventory.rawmaterial"
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="raw_material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventory.rawmaterial"
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventory.warehouse"
            ),
        ),
        migrations.AddConstraint(
            model_name="stock",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("tenant_id", "warehouse", "raw_material"),
                name="unique_stock_per_warehouse",
            ),
        ),
    ]
