# Generated by Django 5.2.7 on 2026-05-04 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='confirmed_unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='direct_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='labour_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='moulding_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='use_calculated_cost',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productmaterial',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.unit'),
        ),
        migrations.AddField(
            model_name='unit',
            name='base_quantity',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name='unit',
            name='breakdown_quantity',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name='unit',
            name='breakdown_unit',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='packaging_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('RAW_MATERIAL', 'Raw Material'), ('ASSEMBLY_PRODUCT', 'Assembly Product'), ('FINISHED_GOOD', 'Finished Good'), ('READY_MADE', 'Ready Made'), ('MANUFACTURED', 'Manufactured')], max_length=20),
        ),
    ]
