# Generated by Django 5.1.3 on 2026-05-06 18:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_rawmaterial_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCostHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('source_type', models.CharField(choices=[('PURCHASE_INVOICE', 'Purchase Invoice'), ('PURCHASE_RETURN', 'Purchase Return'), ('PRODUCTION', 'Production'), ('SALES_INVOICE', 'Sales Invoice'), ('SALES_RETURN', 'Sales Return')], max_length=40)),
                ('source_id', models.UUIDField()),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=14)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('running_quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('running_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('average_cost_after', models.DecimalField(decimal_places=4, max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_history', to='inventory.product')),
            ],
            options={
                'ordering': ['date', 'created_at', 'id'],
                'indexes': [models.Index(fields=['tenant_id', 'product', 'date'], name='inventory_p_tenant__cddfeb_idx'), models.Index(fields=['tenant_id', 'source_type', 'source_id'], name='inventory_p_tenant__e6c077_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductCostState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('total_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('average_cost', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_states', to='inventory.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant_id', 'product'), name='unique_active_product_cost_state')],
            },
        ),
    ]
