# Generated by Django 5.2.7 on 2026-05-09 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_productcosthistory_productcoststate'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaterial',
            name='component_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_in_assemblies', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='productmaterial',
            name='component_type',
            field=models.CharField(choices=[('RAW_MATERIAL', 'Raw Material'), ('FINISHED_GOOD', 'Finished Good')], default='RAW_MATERIAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='productmaterial',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.rawmaterial'),
        ),
    ]
